# Generated by Django 4.2.5 on 2023-10-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogsNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_attempt', models.DateTimeField(auto_now_add=True, verbose_name='дата и время последней попытки')),
                ('attempt_status', models.BooleanField(default=True, verbose_name='статус попытки')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
            ],
            options={
                'verbose_name': 'логи',
                'verbose_name_plural': 'логи',
            },
        ),
        migrations.CreateModel(
            name='NewsletterMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter_name', models.CharField(max_length=100, verbose_name='тема письма')),
                ('newsletter_body', models.TextField(verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'сообщение для рассылки',
                'verbose_name_plural': 'сообщения для рассылок',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsletter_start', models.DateField(verbose_name='начало рассылки')),
                ('newsletter_finish', models.DateField(verbose_name='окончание рассылки')),
                ('frequency', models.CharField(choices=[('Раз в день', 'Раз в день'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], max_length=15, verbose_name='периодичность')),
                ('status', models.CharField(blank=True, default='Создана', max_length=20, null=True, verbose_name='статус рассылки')),
            ],
            options={
                'verbose_name': 'настройки рассылки',
                'verbose_name_plural': 'настройки рассылок',
            },
        ),
    ]
