# Generated by Django 4.2.5 on 2023-10-11 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='newslettermessage',
            name='newsletter_settings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.newslettersettings', verbose_name='настройки рассылки'),
        ),
        migrations.AddField(
            model_name='newslettermessage',
            name='to_email',
            field=models.ManyToManyField(to='client.client'),
        ),
        migrations.AddField(
            model_name='newslettermessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='logsnewsletter',
            name='newsletter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.newslettermessage'),
        ),
    ]
